sdk:
  - changed-files:
      - any-glob-to-any-file: javscript_sdk/**
logstf:
  - changed-files:
      - any-glob-to-any-file: logstf/**
etf2l:
  - changed-files:
      - any-glob-to-any-file: etf2l/**
rgl:
  - changed-files:
      - any-glob-to-any-file: rgl/**
demostf:
  - changed-files:
      - any-glob-to-any-file: demostf/**
