name: Publish Javascript SDK
on:
  push:
    branches:
      - main
    paths:
      - 'javascript-sdk/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish